logging_level: DEBUG
version: v0.0.5
owl_env_path: ../.env
app_index_path: /app/athena/routers/index.html
owl_glossary_path: /app/athena/config/glossary.json
owl_agents_path: /app/athena/config/agents.yaml
owl_tools_path: /app/athena/config/tools.yaml
owl_prompts_path: /app/athena/config/prompts.yaml
owl_agent_content_collection_name: base_collection
owl_agent_content_file_path: /app/file_content
owl_agent_vs_path: /app/chromadb
owl_agent_vs_embedding_fct: OpenAIEmbeddings
owl_agent_llm_history_length: 5
owl_agent_tool_factory_class:  athena.llm.tools.tool_mgr.DefaultToolInstanceFactory
owl_agent_decision_service_fct_name: athena.itg.decisions.nba_ds_dummy.callDecisionService

watsonx_ai_url: https://us-south.ml.cloud.ibm.com
watsonx_ai_project_id: bddd370f-77c3-4b6e-a18b-3ef7f4ca1bae
watsonx_ai_model: "ibm/granite-13b-instruct-v2"
